apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: bmgcpjx/go-demo-6
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/bmgcpjx/go-demo-6:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/bmgcpjx/go-demo-6:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: go-demo-6
        chartPath: charts/go-demo-6
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/bmgcpjx/go-demo-6'
          image.tag: '{{.DIGEST_HEX}}'
